version: '2'
services:
  test:
    build: ./api
    command: python -u tests/main.py
    expose:
      - "5000"
    ports:
      - "12100:5000"
    volumes:
      - ./api:/code
    links:
      - db
  db:
    image: mongo:3.4
    command: --smallfiles --rest